-- Proof of mechanism for ADR 0012 (worker tenant context: scoped non-superuser
-- role + transaction-local `app.tenant_id` GUC).
--
-- WHY THIS FILE EXISTS
-- Phase 0.5C's instruction is that ADR 0012 must NOT be accepted until
-- executable tests prove its properties. ADR 0012's own acceptance criterion
-- names tests over `ops.*` -- but `ops` does not exist and Phase 0.5 must not
-- create it, so that criterion cannot be met and the ADR would sit unfalsifiable
-- indefinitely.
--
-- This file proves the MECHANISM instead of the engine. It builds a throwaway
-- schema, role, table and policies that have exactly the shape ADR 0012
-- specifies, asserts the properties against them, and rolls the whole thing
-- back. NOTHING HERE PERSISTS: no `ops` schema, no engine table, no role, no
-- grant. Verified by the final block, which runs after the rollback.
--
-- What this can and cannot settle is stated at the bottom, and mirrored in the
-- ADR. It moves ADR 0012 from "unverifiable design" to "mechanism verified,
-- integration unverified". It does not, on its own, accept the ADR.

\set ON_ERROR_STOP on

begin;

create schema adr0012_probe;

-- 1. The worker role. ADR 0012 requires: not superuser, no BYPASSRLS.
create role adr0012_worker nologin;
grant usage on schema adr0012_probe to adr0012_worker;

-- Reassigning ownership below needs membership in the target role. Note that
-- `postgres` is NOT superuser on Supabase (measured: rolsuper=false), so this
-- cannot be skipped -- and the same rule is why several REVOKEs elsewhere in
-- this repository are accepted and then silently ignored.
--
-- The role name is interpolated rather than written as the `current_user`
-- keyword. `grant <role> to current_user;` SEGFAULTS this server build --
-- observed 2026-09-11 on Postgres 15.8 (supabase/postgres): "server process was
-- terminated by signal 11", taking the whole instance into crash recovery.
-- Resolving the name to a literal identifier first avoids that code path.
do $$
begin
  execute format('grant adr0012_worker to %I', current_user);
end
$$;

create table adr0012_probe.job (
  id        bigint generated by default as identity primary key,
  tenant_id uuid not null,
  payload   text not null
);

-- `force` is the part that matters and that no table in this repository uses
-- today: without it the table OWNER bypasses every policy, and the worker role
-- is the owner of the engine's tables in most deployment shapes.
alter table adr0012_probe.job enable row level security;
alter table adr0012_probe.job force row level security;

-- Making the worker the OWNER is deliberately the harsher test: an owner
-- bypasses RLS unless `force` is set, so if `force` were missing every
-- assertion below would pass vacuously. (Postgres requires a new owner to hold
-- CREATE on the schema, hence the grant.) The real ops_worker need not own its
-- tables -- this proves the property even when it does.
grant create on schema adr0012_probe to adr0012_worker;
alter table adr0012_probe.job owner to adr0012_worker;

-- 2. One SECURITY DEFINER helper that every policy reads, per ADR 0012 item 4.
--    `current_setting(..., true)` returns NULL when unset -- that NULL is what
--    makes the policy match nothing instead of everything.
create function adr0012_probe.current_tenant_id() returns uuid
  language sql stable security definer set search_path to ''
  as $fn$ select nullif(current_setting('app.tenant_id', true), '')::uuid $fn$;

create policy job_tenant_scoped on adr0012_probe.job
  for all to adr0012_worker
  using (tenant_id = adr0012_probe.current_tenant_id())
  with check (tenant_id = adr0012_probe.current_tenant_id());

grant select, insert, update, delete on adr0012_probe.job to adr0012_worker;

-- service_role is given ordinary, minimal access so that block F measures RLS
-- rather than the grant layer. The point of that block is that plain SELECT is
-- enough for service_role to see every tenant, because BYPASSRLS means no
-- policy is ever consulted -- the grant is not what is being tested.
grant usage on schema adr0012_probe to service_role;
grant select on adr0012_probe.job to service_role;

insert into adr0012_probe.job (tenant_id, payload) values
  ('11111111-1111-1111-1111-111111111111', 'tenant A work'),
  ('11111111-1111-1111-1111-111111111111', 'more tenant A work'),
  ('22222222-2222-2222-2222-222222222222', 'tenant B work');

-- ===========================================================================
-- A. THE ROLE CARRIES NO BLANKET CAPABILITY
--    "no superuser, avoid BYPASSRLS" is the owner requirement that the whole
--    design rests on; a role with either makes every policy below decorative.
-- ===========================================================================

do $$
declare r record;
begin
  select rolsuper, rolbypassrls, rolcreaterole, rolcreatedb
    into r from pg_roles where rolname = 'adr0012_worker';

  if r.rolsuper then raise exception 'the worker role is SUPERUSER'; end if;
  if r.rolbypassrls then raise exception 'the worker role has BYPASSRLS'; end if;
  if r.rolcreaterole then raise exception 'the worker role has CREATEROLE'; end if;
  if r.rolcreatedb then raise exception 'the worker role has CREATEDB'; end if;
end
$$;

-- ===========================================================================
-- B. EXPLICIT TENANT CONTEXT SCOPES READS
-- ===========================================================================

do $$
declare v_n bigint;
begin
  set local role adr0012_worker;
  perform set_config('app.tenant_id', '11111111-1111-1111-1111-111111111111', true);

  select count(*) into v_n from adr0012_probe.job;
  if v_n <> 2 then
    raise exception 'tenant A sees % job rows, expected its own 2', v_n;
  end if;

  select count(*) into v_n from adr0012_probe.job
   where tenant_id = '22222222-2222-2222-2222-222222222222';
  if v_n <> 0 then
    raise exception 'tenant A can read tenant B rows';
  end if;

  reset role;
end
$$;

-- ===========================================================================
-- C. MISSING CONTEXT SEES ZERO ROWS, NOT ALL ROWS
--    This is the single property that distinguishes this design from "filter in
--    application code". A worker that forgets to set the GUC must read an empty
--    database.
-- ===========================================================================

do $$
declare v_n bigint;
begin
  set local role adr0012_worker;
  perform set_config('app.tenant_id', '', true);

  select count(*) into v_n from adr0012_probe.job;
  if v_n <> 0 then
    raise exception
      'with NO tenant context the worker read % rows; missing context must fail closed, not open', v_n;
  end if;

  reset role;
end
$$;

-- A malformed context must not degrade to "see everything" either. It should
-- raise, because a worker handed a corrupt tenant id is in an unknown state.
do $$
declare
  v_n      bigint;
  v_raised boolean := false;
begin
  set local role adr0012_worker;
  perform set_config('app.tenant_id', 'not-a-uuid', true);
  begin
    select count(*) into v_n from adr0012_probe.job;
  exception when others then
    v_raised := true;
  end;
  reset role;

  if not v_raised and v_n <> 0 then
    raise exception 'a malformed tenant id read % rows', v_n;
  end if;
end
$$;

-- ===========================================================================
-- D. TENANT A CANNOT MUTATE TENANT B
--    Using UNQUALIFIED statements. Mutation-testing the public-schema suite
--    proved that a targeted `... where id = <B>` is masked by the SELECT policy
--    and stays green even when the UPDATE policy is wide open. The unqualified
--    form is the one that actually exercises the write policy.
-- ===========================================================================

do $$
declare
  v_n              bigint;
  v_insert_blocked boolean := false;
begin
  set local role adr0012_worker;
  perform set_config('app.tenant_id', '11111111-1111-1111-1111-111111111111', true);

  update adr0012_probe.job set payload = 'hijacked';
  get diagnostics v_n = row_count;
  if v_n <> 2 then
    raise exception 'an unqualified update touched % rows, expected only tenant A''s 2', v_n;
  end if;

  delete from adr0012_probe.job;
  get diagnostics v_n = row_count;
  if v_n <> 2 then
    raise exception 'an unqualified delete removed % rows, expected only tenant A''s 2', v_n;
  end if;

  begin
    insert into adr0012_probe.job (tenant_id, payload)
    values ('22222222-2222-2222-2222-222222222222', 'planted into B');
  exception when insufficient_privilege then
    v_insert_blocked := true;
  end;
  if not v_insert_blocked then
    raise exception 'the worker inserted a row belonging to another tenant';
  end if;

  reset role;

  -- Confirm from outside the worker's own view that tenant B survived intact.
  select count(*) into v_n from adr0012_probe.job
   where tenant_id = '22222222-2222-2222-2222-222222222222'
     and payload = 'tenant B work';
  if v_n <> 1 then
    raise exception 'tenant B''s row did not survive tenant A''s unqualified writes';
  end if;
end
$$;

-- ===========================================================================
-- E. `force row level security` REALLY BINDS THE OWNER
--    The worker role OWNS this table. Without `force`, ownership alone would
--    bypass every policy above and each assertion would have been vacuous.
-- ===========================================================================

do $$
declare v_forced boolean;
begin
  select relforcerowsecurity into v_forced
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'adr0012_probe' and c.relname = 'job';
  if not v_forced then
    raise exception 'force row level security is off; the owning worker role would bypass every policy';
  end if;
end
$$;

-- ===========================================================================
-- F. WHY THE WORKER MUST NOT BE service_role -- CHARACTERISED
--    service_role is granted BYPASSRLS by the platform. Running the worker as
--    service_role would make every assertion above unreachable. This block
--    PASSES when service_role bypasses; it documents a capability, it does not
--    verify a protection.
-- ===========================================================================

do $$
declare
  v_n       bigint;
  v_bypass  boolean;
begin
  select rolbypassrls into v_bypass from pg_roles where rolname = 'service_role';

  set local role service_role;
  perform set_config('app.tenant_id', '', true);
  select count(*) into v_n from adr0012_probe.job;
  reset role;

  if not (v_bypass or v_n > 0) then
    raise exception
      'service_role no longer bypasses RLS (bypassrls=%, rows with no tenant context=%). If the platform changed, revisit ADR 0012 and this block together.',
      v_bypass, v_n;
  end if;
end
$$;

-- Leave a sentinel set as the last act of this transaction, so the rollback
-- check in block G has something real to look for rather than block F's ''.
select set_config('app.tenant_id', 'deadbeef-0000-0000-0000-0000000000aa', true);

rollback;

-- ===========================================================================
-- G. TRANSACTION-LOCALITY ON A REUSED CONNECTION
--    ADR 0012 item 2 forbids connection-level SET because a pooled connection
--    would carry one job's tenant into the next.
--
--    This has to COMMIT to mean anything, and that is not obvious. A rollback
--    reverts a plain `SET` as well as a `SET LOCAL` -- GUC changes are
--    transactional -- so checking after the rollback above passes whether or
--    not `is_local` was used. Mutation-testing exposed that: switching every
--    `set_config(..., true)` to `false` left the suite green until this block
--    was rewritten to commit.
--
--    Committing a GUC assignment leaves no database artifact -- no row, no
--    object -- so this stays consistent with "the suite leaves no trace".
-- ===========================================================================

-- First the weaker case: the rolled-back transaction above must not leak.
do $$
declare v_leaked text;
begin
  v_leaked := current_setting('app.tenant_id', true);
  if v_leaked is not null and v_leaked <> '' then
    raise exception
      'app.tenant_id survived a ROLLED BACK transaction on the same connection (value %)', v_leaked;
  end if;
end
$$;

-- Now the case that actually discriminates: a COMMITTED transaction, which is
-- what a worker finishing a job really does.
begin;
select set_config('app.tenant_id', 'deadbeef-0000-0000-0000-00000000ffff', true);
commit;

do $$
declare v_leaked text;
begin
  v_leaked := current_setting('app.tenant_id', true);
  if v_leaked is not null and v_leaked <> '' then
    raise exception
      'app.tenant_id survived a COMMITTED transaction on the same connection (value %). The next job on this pooled connection would inherit the previous tenant''s context -- use set_config(..., true) / SET LOCAL, never a connection-level SET.', v_leaked;
  end if;
end
$$;

-- ===========================================================================
-- H. NOTHING PERSISTED
-- ===========================================================================

do $$
begin
  if exists (select 1 from pg_namespace where nspname = 'adr0012_probe') then
    raise exception 'the probe schema survived; this suite must leave no trace';
  end if;
  if exists (select 1 from pg_roles where rolname = 'adr0012_worker') then
    raise exception 'the probe role survived; this suite must leave no trace';
  end if;
end
$$;

-- ===========================================================================
-- WHAT THIS PROVES, AND WHAT IT DOES NOT
--
-- PROVEN (mechanism):
--   * a non-superuser, non-BYPASSRLS role can be scoped by a GUC-backed policy
--   * explicit tenant context scopes reads
--   * ABSENT context yields zero rows, not all rows
--   * a malformed context does not degrade to "see everything"
--   * unqualified UPDATE/DELETE/INSERT cannot cross the tenant boundary
--   * `force row level security` binds the owning role
--   * transaction-local context does not survive onto a reused connection
--
-- NOT PROVEN (integration -- these need the engine that Phase 0.5 must not build):
--   * that a real worker derives tenant_id from the LEASED JOB ROW rather than
--     from an argument (ADR 0012 item 3). That is the property that makes the
--     context server-side, and it is untestable until a job table and a leasing
--     path exist.
--   * that no production code path sets the GUC outside a transaction.
--   * that engine components stop using service_role. Today the edge functions
--     DO use it -- see block F, and `rls_tenant_isolation.sql` section 6.
--
-- ADR 0012 therefore stays PROPOSED. The mechanism is no longer a hypothesis;
-- the integration is still entirely unbuilt.
-- ===========================================================================
