--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint,
    pipeline_stage text not null default 'new_lead',
    stage_entered_at timestamp with time zone not null default now(),
    loss_reason_id bigint,
    lost_at timestamp with time zone,
    converted_at timestamp with time zone,
    next_action_at timestamp with time zone,
    -- No CHECK enumerating pipeline stages. Stage vocabulary is tenant
    -- CONFIGURATION, not schema semantics (ADR 0013): a nine-value clinic
    -- pipeline frozen into DDL is exactly what stops a second tenant being
    -- onboarded without a migration. The database validates structural
    -- integrity (NOT NULL, default, index); which stages exist and what they
    -- are called is data, as `loss_reasons` already is.
    constraint deals_lost_requires_reason check (
        lost_at is null or loss_reason_id is not null
    )
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null default false,
    role text not null default 'operator' check (role in ('owner', 'operator')),
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

-- Minimal commercial lead metadata. This CRM intentionally stores no clinical data.
create table public.lead_profiles (
    id bigint generated by default as identity primary key,
    contact_id bigint not null unique,
    acquired_at timestamp with time zone not null default now(),
    last_interaction_at timestamp with time zone,
    next_action_at timestamp with time zone,
    -- Same rule as deals.pipeline_stage: tenant vocabulary, not DDL. ADR 0013.
    operational_status text not null default 'active',
    do_not_contact boolean not null default false,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

-- Attribution is kept separate so future acquisition channels do not overload contacts.
create table public.acquisition_attributions (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    acquired_at timestamp with time zone not null default now(),
    source text,
    medium text,
    campaign text,
    campaign_id text,
    ad_group text,
    ad_group_id text,
    ad text,
    ad_id text,
    keyword text,
    match_type text,
    landing_page text,
    utm_source text,
    utm_medium text,
    utm_campaign text,
    utm_content text,
    utm_term text,
    gclid text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table public.loss_reasons (
    id bigint generated by default as identity primary key,
    code text not null unique,
    label text not null,
    active boolean not null default true,
    sort_order integer not null default 0
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deals
    add constraint deals_loss_reason_id_fkey foreign key (loss_reason_id) references public.loss_reasons(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.lead_profiles
    add constraint lead_profiles_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.acquisition_attributions
    add constraint acquisition_attributions_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);
create index deals_pipeline_stage_idx on public.deals using btree (pipeline_stage) where lost_at is null and archived_at is null;
create index deals_loss_reason_id_idx on public.deals using btree (loss_reason_id) where loss_reason_id is not null;
create index lead_profiles_contact_id_idx on public.lead_profiles using btree (contact_id);
create index lead_profiles_next_action_at_idx on public.lead_profiles using btree (next_action_at) where do_not_contact = false;
create index acquisition_attributions_contact_id_idx on public.acquisition_attributions using btree (contact_id);
