// Agent run requests — the one owner service that asks for a model invocation.
//
// The authority, the gates, the idempotency, the lineage and the kill switch all
// live in ops.request_agent_run (supabase/migrations/20260914120000_…, section
// 6). This module adds what TypeScript can, exactly as companyOs.ts does: typed
// input, fast rejection of input that can never be valid, and typed errors. It
// calls one function and never assembles a row.
//
// WHAT A REQUEST IS. The explicit ask for ONE run of one capability by the agent
// a task is assigned to. Creating or changing a task never calls a model; only
// this does. It resolves to the run's id even when an execution stop refused the
// run: the refusal is RECORDED, as a cancelled run naming the stop and carrying
// no job (ADR 0010), rather than thrown away.
//
// THE TRUST MODEL (ADR 0016 §5). Three identifiers that are easy to conflate and
// must never stand in for one another:
//
//   idempotency key  caller-chosen DATA, scoped to the tenant: "this is the same
//                    request". The same key for the same request resolves to the
//                    run it created; for a different request it is refused
//                    (invalid_state). It is looked up only inside `tenantId`, so
//                    it selects nothing in another tenant, and it is neither a
//                    secret nor a grant.
//   correlation      system lineage: generated by the database for a new run, or
//                    inherited from the run a retry names. There is no argument
//                    for it, and `app.event_correlation_id`, which any caller can
//                    write, is not read.
//   causation        derived by the database from the run's own facts.
//
// None of them is taken from a model, and none of them grants anything. That is
// why AgentRunRequestContext, unlike companyOs.ts's DomainContext, has no
// correlationId or causationId — and why the call below is built from named
// fields, so a key smuggled onto either object never reaches the database.
//
// WHO CAN CALL THIS IN PHASE 1D: a transaction running as the database owner. No
// application role can execute ops.request_agent_run (asserted in
// supabase/tests/agent_runtime.sql), and a future runtime caller arrives through
// a wrapper that resolves the tenant itself (ADR 0015), never through a postgres
// connection string. `tenantId` is the scope the caller is ALREADY authorised
// for; every other id is untrusted and resolved by the database inside it.

import type { TxClient } from "../db/types.ts";
import { CompanyOsError, toDomainError } from "./errors.ts";

export interface AgentRunRequestContext {
  /** The authorised tenant scope. Never taken from a payload. */
  readonly tenantId: string;
  /** Provenance of the request, recorded as requested_by and on its events. */
  readonly source: string;
}

export interface RequestAgentRunInput {
  readonly taskId: string;
  /** Must be the agent the task is assigned to; the database decides. */
  readonly agentId: string;
  /**
   * Engine vocabulary, e.g. "task_assessment". Only its shape is checked here:
   * whether it exists is ops.agent_run_capabilities()'s answer.
   */
  readonly capability: string;
  /** Caller-chosen, tenant-scoped deduplication data. Grants nothing. */
  readonly idempotencyKey: string;
  /** A FINISHED run of the same task, agent and capability that this repeats. */
  readonly retryOfRunId?: string;
}

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const SOURCE = /^[a-z][a-z0-9_.:-]{0,127}$/;
// The shapes of ops.agent_runs' CHECK constraints and of the function's own
// refusals, character for character. Both are ASCII-only, so a JS length and
// char_length agree.
const CAPABILITY = /^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*$/;
const MAX_CAPABILITY_LENGTH = 100;
const IDEMPOTENCY_KEY = /^[\x21-\x7e]{1,200}$/;

function requireUuid(value: unknown, field: string): string {
  if (typeof value !== "string" || !UUID.test(value)) {
    throw new CompanyOsError("malformed_identifier", `${field} is not a uuid`);
  }
  return value;
}

function optionalUuid(value: unknown, field: string): string | null {
  return value === undefined || value === null
    ? null
    : requireUuid(value, field);
}

function requireTenant(value: unknown): string {
  if (value === undefined || value === null || value === "") {
    throw new CompanyOsError("missing_tenant_scope", "no tenant scope");
  }
  return requireUuid(value, "tenantId");
}

function requireShape(
  value: unknown,
  shape: RegExp,
  maxLength: number,
  message: string,
): string {
  if (
    typeof value !== "string" ||
    value.length > maxLength ||
    !shape.test(value)
  ) {
    throw new CompanyOsError("invalid_argument", message);
  }
  return value;
}

/**
 * Requests one agent run and resolves to its id. The same (tenant, key, request)
 * resolves to the same id every time; nothing is created twice.
 *
 * `async`, so invalid input REJECTS the returned promise rather than throwing
 * before one exists.
 */
export async function requestAgentRun(
  tx: TxClient,
  context: AgentRunRequestContext,
  input: RequestAgentRunInput,
): Promise<string> {
  // Exactly seven positions, each read from a named field: nothing else on
  // `context` or `input` can become an argument.
  const params = [
    requireTenant(context.tenantId),
    requireUuid(input.taskId, "taskId"),
    requireUuid(input.agentId, "agentId"),
    requireShape(
      input.capability,
      CAPABILITY,
      MAX_CAPABILITY_LENGTH,
      "capability is missing or malformed",
    ),
    requireShape(
      input.idempotencyKey,
      IDEMPOTENCY_KEY,
      200,
      "idempotencyKey must be 1 to 200 printable ASCII characters",
    ),
    requireShape(context.source, SOURCE, 128, "source is missing or malformed"),
    optionalUuid(input.retryOfRunId, "retryOfRunId"),
  ] as const;

  let id: unknown;
  try {
    const { rows } = await tx.query<{ result: unknown }>(
      "select ops.request_agent_run($1, $2, $3, $4, $5, $6, $7) as result",
      params,
    );
    id = rows[0]?.result;
  } catch (error) {
    throw toDomainError(error);
  }
  if (typeof id !== "string") {
    throw new Error("the database returned no agent run id");
  }
  return id;
}
