// The reviewed screening vocabulary for a Brazilian health service's reception
// (ADR 0023 §C), matched against normalised text (lower case, no accents).
//
// A pack is a security control, not tenant vocabulary: it decides what never
// reaches a model, so it lives in reviewed code with a synthetic corpus test
// and mutation checks, and a tenant only selects it by id. Changing any list
// is a new pack version (health_pt_br.v2), never an edit of this one, because
// screenings record the pack id they ran with.
//
// Bias: a sensitive pattern that also catches an innocent clause costs a
// clause the model does not see; a missing one leaks. When in doubt, a word is
// sensitive. Administrative patterns are what the reception may serve.

import type { SanitizerPack } from "../messageSanitizer.ts";

const CRISIS: readonly RegExp[] = [
  /\bsuicid/,
  /\b(me|se) matar\b/,
  /\bme mato\b/,
  /\bmatar a mim\b/,
  /\btirar a (minha )?(propria )?vida\b/,
  /\btirar minha (propria )?vida\b/,
  /\bacabar com (a )?minha vida\b/,
  /\bacabar com tudo\b/,
  /\bnao (quero|aguento) (mais )?viver\b/,
  /\b(quero|vou|queria) morrer\b/,
  /\b(vontade|desejo) de morrer\b/,
  /\bpensando em morrer\b/,
  /\bmelhor (eu )?(estar |ficar )?mort[oa]\b/,
  /\bmelhor sem mim\b/,
  /\bsumir (do mundo|pra sempre|para sempre)\b/,
  /\bme (cortar|corto|cortei|cortando|machucar|machuco|machuquei|machucando|ferir|firo|feri)\b/,
  /\bautomutil/,
  /\bauto ?-?(lesao|mutilacao|agressao)\b/,
  /\boverdose\b/,
  /\btomar (todos|todas) os (remedios|comprimidos)\b/,
  /\bme (jogar|atirar) (da|de|do|na|no|em)\b/,
  /\bpular (da|do|de) (janela|ponte|predio|sacada)\b/,
  /\bme enforcar\b/,
  /\b(fui|estou sendo|to sendo|sou) (abusad[oa]|estuprad[oa]|agredid[oa]|espancad[oa])\b/,
  /\bestupr/,
  /\babuso sexual\b/,
  /\b(ele|ela) me (bate|batia|agride|agrediu|ameaca|ameacou|espanca)\b/,
  /\bameac\w* (de )?me matar\b/,
  /\b(vou|quero|vontade de) matar\b/,
  /\bviolencia domestica\b/,
  /\b(corro|correndo) (risco|perigo)\b/,
  /\bestou em perigo\b/,
  /\bemergencia\b/,
];

const SENSITIVE: readonly RegExp[] = [
  // Conditions, diagnoses, medicines, care.
  /\bansie/,
  /\bansios/,
  /\bdepress/,
  /\bpanico\b/,
  /\bcrises?\b/,
  /\btoc\b/,
  /\btdah\b/,
  /\bdeficit de atencao\b/,
  /\bhiperativ/,
  /\bbipolar/,
  /\bborderline\b/,
  /\besquizo/,
  /\bpsicos/,
  /\bpsicotic/,
  /\bsurt/,
  /\bautis/,
  /\btea\b/,
  /\bespectro\b/,
  /\bburn ?out\b/,
  /\bestress/,
  /\bstress/,
  /\btrauma/,
  /\bluto\b/,
  /\bfobia/,
  /\binsonia\b/,
  /\bcompuls/,
  /\btranstorno/,
  /\bsindrome\b/,
  /\bdiagnost/,
  /\blaudo/,
  /\bmedica(cao|coes|mento|mentos|do|da|r)\b/,
  /\bremedio/,
  /\bantidepress/,
  /\bansiolit/,
  /\b(clonazepam|rivotril|sertralina|fluoxetina|escitalopram|venlafaxina|bupropiona|quetiapina|litio|ritalina|venvanse|zolpidem|amitriptilina|paroxetina|citalopram|alprazolam|diazepam|pregabalina|lamotrigina)\b/,
  /\bpsiquiatr/,
  /\bneurolog/,
  /\binterna(d[oa]|cao|r)\b/,
  /\bcaps\b/,
  /\bsaude mental\b/,
  /\bsintoma/,
  // States and feelings.
  /\btrist/,
  /\bchor(o|ando|ar|ei|a|ava)\b/,
  /\bsozinh/,
  /\bsolida/,
  /\bvazi[oa]\b/,
  /\bangusti/,
  /\bdesesper/,
  /\bmedos?\b/,
  /\bnervos/,
  /\birrita/,
  /\bexaust/,
  /\bsofr(o|endo|imento|er|i|ia)\b/,
  /\bdor(es)?\b/,
  /\b(estou|to|tou|ando|fico|ficando|me sinto|sinto|sentindo) (muito |meio |bem |tao )?mal\b/,
  /\bnao (ando|estou|to|tou|fico|me sinto) bem\b/,
  /\bme sinto\b/,
  /\bsentindo\b/,
  /\bsinto (que|muita|muito|uma|um)\b/,
  /\bpassando por\b/,
  /\b(fase|momento|epoca|periodo|dias?) (muito |bem |tao )?(dificil|dificeis|complicad|ruim|ruins|pesad|horrivel|horriveis)/,
  /\bdificil (lidar|aceitar|superar)/,
  /\bproblemas? (emocion|psicolog|de saude|mental|mentais|familiar|familiares|conjug|no casamento|de relacionamento|com (meu|minha|o|a))/,
  /\bemocion/,
  /\braiva\b/,
  /\bculpa\b/,
  /\bvergonha\b/,
  /\bautoestima\b/,
  /\bauto estima\b/,
  /\binsegur/,
  /\bcarenc/,
  /\brejeic/,
  /\bfrustr/,
  /\bdesanim/,
  /\bdesmotiv/,
  /\bcansa(d|co|ca)/,
  /\bpreocupa/,
  /\bpensamentos?\b/,
  /\bmemoria\b/,
  /\bconcentra(cao|r)\b/,
  /\besquec/,
  // Relationships, family, grief, abuse.
  /\babusiv/,
  /\babuso\b/,
  /\bassedi/,
  /\bbullying\b/,
  /\bviolencia\b/,
  /\bagress/,
  /\bseparac/,
  /\bdivorci/,
  /\btrai(u|ram|cao|coes|do|da)\b/,
  /\bciume/,
  /\btermin(ei|ou|amos) (com|o namoro|o casamento)\b/,
  /\btermino\b/,
  /\bbrig(a|as|amos|ando|o)\b/,
  /\bfalec/,
  /\bmorreu\b/,
  /\bmorte\b/,
  /\bperdi (meu|minha|o meu|a minha|o|a) (pai|mae|filh|marido|esposa|irm|av|amig|namorad|emprego)/,
  // Substances, eating, sleep, body.
  /\bvici(o|ad)/,
  /\balcool/,
  /\bbebida\b/,
  /\bbebendo\b/,
  /\bbebo (muito|demais|todo)\b/,
  /\bdrogas?\b/,
  /\b(maconha|cocaina|crack)\b/,
  /\bdependen(cia|te) (quimic|de)/,
  /\bapostas?\b/,
  /\banorex/,
  /\bbulim/,
  /\bcompulsao\b/,
  /\bapetite\b/,
  /\bpeso\b/,
  /\bobesi/,
  /\bsono\b/,
  /\bdorm(ir|indo|i|o|e)\b/,
  /\bdurm(o|imos)\b/,
  /\bpesadel/,
  /\bgravid/,
  /\bgestant/,
  /\bgestacao\b/,
  /\bpos ?-?parto\b/,
  /\baborto\b/,
  /\binfertil/,
  /\bdoen(ca|cas|te)\b/,
  /\bcancer\b/,
  /\btumor\b/,
  /\bhiv\b/,
  /\bcronic/,
  /\bfalta de ar\b/,
  /\btaquicardia\b/,
  /\b(coracao|peito) (acelerado|apertado|disparado|disparando)\b/,
  /\btrem(edeira|or|endo)\b/,
  // Intimate life (LGPD art. 5 II), treatment history.
  /\bsexua/,
  /\bsexo\b/,
  /\blibido\b/,
  /\b(gay|lesbica|bissexual|transgenero|transexual)\b/,
  /\b(ja|antes) (fiz|fazia|faco|tentei) (terapia|tratamento|acompanhamento|analise)\b/,
  /\bmeu (antigo |ultimo )?(psicologo|terapeuta|psiquiatra|medico|neurologista)\b/,
  /\bminha (antiga |ultima )?(psicologa|terapeuta|psiquiatra|medica|neurologista)\b/,
  /\bem tratamento\b/,
  /\bfaco tratamento\b/,
  // Being in care is itself health data: the database already tells the
  // model a client is a client (partyKind), so the clause adds nothing.
  /\b(sou|ja sou|era|fui) paciente\b/,
  /\bpreciso de ajuda\b/,
];

const ADMINISTRATIVE: readonly RegExp[] = [
  /\bhorario/,
  /\bhoras?\b/,
  /\b\d{1,2} ?(h|hs|hrs|horas)\b/,
  /\b\d{1,2}:\d{2}\b/,
  /\bagend/,
  /\bmarc(ar|o|ou|acao|ado|ada|amos)\b/,
  /\bremarc/,
  /\bdesmarc/,
  /\bcancel/,
  /\bdisponi/,
  /\bvagas?\b/,
  /\bencaixe\b/,
  /\bdatas?\b/,
  /\bsemana/,
  /\bmes\b/,
  /\bmanha\b/,
  /\btarde\b/,
  /\bnoite\b/,
  /\b(segunda|terca|quarta|quinta|sexta)(-feira| feira)?\b/,
  /\b(sabado|domingo)\b/,
  /\b(hoje|amanha)\b/,
  /\bfim de semana\b/,
  /\b\d{1,2}\/\d{1,2}\b/,
  /\bvalor/,
  /\bprec(o|os)\b/,
  /\bcust(a|o|am)\b/,
  /\bquanto\b/,
  /\bpag(ar|o|amento|amentos|uei|ou|ando)\b/,
  /\bpix\b/,
  /\bcartao\b/,
  /\bboleto\b/,
  /\bparcel/,
  /\bdesconto/,
  /\bpacotes?\b/,
  /\bplanos?\b/,
  /\bconvenio/,
  /\breembolso/,
  /\brecibo/,
  /\bnota fiscal\b/,
  /\btransferencia\b/,
  /\bcomprovante/,
  /\breais\b/,
  /r\$/,
  /\bconsultas?\b/,
  /\bsess(ao|oes)\b/,
  /\batendi(mento|mentos|da|do|dos)\b/,
  /\batende(m)?\b/,
  /\bterapia\b/,
  /\bpsicolog/,
  /\bprofissional\b/,
  /\bonline\b/,
  /\bpresencia/,
  /\bvideo/,
  /\bchamada\b/,
  /\b(meet|zoom)\b/,
  /\bendereco/,
  /\bonde (fica|ficam|e)\b/,
  /\blocaliza/,
  /\bduracao\b/,
  /\b(quanto tempo|quantos minutos) (dura|leva)\b/,
  /\bdura quanto\b/,
  /\bminutos\b/,
  /\bcomo funciona/,
  /\bfunciona/,
  /\binforma/,
  /\bduvida/,
  /\bprimeira (consulta|sessao|vez|conversa)\b/,
  /\bclinica\b/,
  /\bfrequencia\b/,
  /\b(semanal|quinzenal|mensal)\b/,
  /\blink\b/,
  /\bconfirm/,
  /\blembrete/,
  /\bresponsavel\b/,
  /\bidade\b/,
  /\b\d{1,2} anos\b/,
  /\b(adolescente|crianca|adulto|casal|casais|idoso)s?\b/,
  /\b(instagram|site|google)\b/,
  /\bindica(cao|ou|ram|da|do)\b/,
  /\bcontato\b/,
  /\bwhats(app)?\b/,
  /\bcomecar\b/,
  /\be-?mail\b/,
  /\bformato\b/,
  /\bmodalidade\b/,
];

// Whole-clause acknowledgements, read after punctuation is removed.
const BENIGN: readonly RegExp[] = [
  /^(oi+|ola|opa|e ai|eai|bom dia|boa tarde|boa noite|tudo (bem|bom|certo|joia)( com voce| e voce| e vc)?|td bem|como vai|obrigad[oa]( pela atencao)?|muito obrigad[oa]|obg|valeu|vlw|ok|okay|certo|sim|nao|claro|pode ser|pode|perfeito|combinado|beleza|blz|entendi|ta bom|ta|otimo|show|legal|ate (mais|logo|amanha)|tchau|aguardo|fico no aguardo|por favor|pf|pfv|grat[oa]|agradeco|desculp\w*|com licenca|ah|hum+|kk+|haha+|rs+|isso|exato|pronto|feito|ok obrigad[oa])$/,
  /^(meu nome e|me chamo|aqui e) [a-z]+( [a-z]+)?$/,
  /^sou (o|a) [a-z]+$/,
  /^(para|pra) (mim|meu filho|minha filha|meu marido|minha esposa|meu esposo|minha mae|meu pai)$/,
  /^(e )?(para|pra) (voce|vc)$/,
];

// An administrative question that names a sensitive word without speaking
// about the sender. The rest of its clause must still be clean.
const ADMINISTRATIVE_PHRASES: readonly RegExp[] = [
  /\bdiferenca entre (o |a )?psicolog\w* e (o |a )?psiquiatr\w*/,
  /\bdiferenca entre (o |a )?psiquiatr\w* e (o |a )?psicolog\w*/,
  /\b(quanto tempo|como) (dura|funciona|e) (o )?tratamento\b/,
];

const HUMAN_REQUEST: readonly RegExp[] = [
  /\b(falar|conversar) com (um |uma |alguem |a |o )?(humano|humana|pessoa|atendente|recepcionista|gente de verdade|pessoa de verdade|pessoa real|alguem de verdade|alguem real)\b/,
  /\b(falar|conversar) com alguem\b/,
  /\batendimento humano\b/,
  /\b(quero|queria|prefiro|preciso de) (um |uma )?(humano|humana|pessoa|atendente)\b/,
  /\b(voce|vc) e (um |uma )?(robo|bot|ia|inteligencia artificial|maquina)\b/,
  /\be (um )?robo\b/,
];

const OPT_OUT: readonly RegExp[] = [
  /\b(pare|parem|para) de (me )?(mandar|enviar)\b/,
  /\bnao (quero|desejo) (mais )?(receber|mensage)/,
  /\bnao me (mande|mandem|envie|enviem)\b/,
  /\bme (tira|tire|remova|remove|exclua|exclui)\b/,
  /\bdescadastr/,
  /\bsair da lista\b/,
  /^(sair|parar|stop)$/,
];

export const HEALTH_PT_BR_V1: SanitizerPack = Object.freeze({
  id: "health_pt_br.v1",
  crisis: Object.freeze(CRISIS),
  sensitive: Object.freeze(SENSITIVE),
  administrative: Object.freeze(ADMINISTRATIVE),
  administrativePhrases: Object.freeze(ADMINISTRATIVE_PHRASES),
  benign: Object.freeze(BENIGN),
  humanRequest: Object.freeze(HUMAN_REQUEST),
  optOut: Object.freeze(OPT_OUT),
});

/** The reviewed packs a tenant may select. */
export const SANITIZER_PACKS: Readonly<Record<string, SanitizerPack>> =
  Object.freeze({ [HEALTH_PT_BR_V1.id]: HEALTH_PT_BR_V1 });
