-- Durable ingestion ledger for the Postmark inbound-email webhook.
-- Design: docs/design/postmark-ingestion.md. Deviation: docs/adr/0014-inbound-email-ledger-keys-on-recipient-email.md
--
-- WHY THIS IS HAND-WRITTEN (the repo's rule is that migrations are generated):
-- `supabase db diff` needs a running local database to diff against, and the
-- Docker daemon on this machine is down (PHASE_0_5B_DATABASE_VERIFICATION.md).
-- The table is ALSO declared in `supabase/schemas/01_tables.sql`, the policy in
-- `05_policies.sql` and the grants in `06_grants.sql`, deliberately matching
-- this file statement for statement — a table that exists only in a migration
-- is a table the NEXT generated diff drops.
--
-- WHY THE TABLE EXISTS AT ALL:
-- `supabase/functions/postmark/index.ts` discarded the failure Response that
-- `addNoteToContact` returns and answered 200 to every ingestion failure. The
-- provider therefore never retried, and nothing recorded that a message had
-- been lost. Inbound email is the only untrusted external channel that reaches
-- this database, so "lost silently" was the default for the one input path
-- nobody controls.
--
-- LGPD: this table stores inbound email content, which is personal data. RLS is
-- enabled, `anon` gets nothing, `authenticated` gets SELECT gated on
-- `public.is_admin()`, and only `service_role` (the Edge Function) can write.

create table if not exists public.inbound_emails (
    id bigint generated by default as identity primary key,
    -- Postmark's `MessageID`: provider-supplied and stable across its retries.
    message_id text not null,
    -- The recipient this row claims. "" means the failure belongs to the whole
    -- delivery rather than to one recipient (unparseable body, missing field,
    -- attachment upload). Never NULL: see the unique index below.
    recipient_email text not null default '',
    status text not null default 'pending',
    attempts integer not null default 0,
    -- The raw webhook body. Without it a failed ingest cannot be replayed, and
    -- replay is the only thing that makes a failure record more than a log line.
    payload jsonb not null,
    error text,
    received_at timestamp with time zone not null default now(),
    processed_at timestamp with time zone,
    -- Engine vocabulary, not tenant vocabulary: every tenant's ingestion has
    -- exactly these four states, so ADR 0013's test ("would tenant two need a
    -- different set?") answers no and a CHECK is the right tool here.
    constraint inbound_emails_status_check check (
        status in ('pending', 'ingested', 'failed_permanent', 'failed_transient')
    )
);

-- Idempotency, enforced by the index rather than by application code: the
-- webhook INSERTs first and lets this index reject the loser. A
-- SELECT-then-INSERT races under concurrent delivery and produces duplicate
-- notes, which is why the claim is a compare-and-set.
--
-- The recipient is keyed by EMAIL, not by contact id. This departs from
-- docs/design/postmark-ingestion.md §4 for two reasons (ADR 0014):
--   1. The contact does not exist yet when the claim is made — claim-before-work
--      means the claim precedes contact resolution, so there is no id to key on.
--   2. A NULLable column in a unique index deduplicates nothing. Postgres
--      compares NULLs as distinct, so `unique (message_id, recipient_contact_id)`
--      would accept unlimited `(id, NULL)` rows — no dedup for exactly the rows
--      the index exists to protect.
create unique index if not exists uq__inbound_emails__message_recipient
    on public.inbound_emails using btree (message_id, recipient_email);

-- The states are the triage interface (design §6): `pending` older than N
-- minutes is a request that died mid-work, `failed_transient` with rising
-- `attempts` is a dependency that is down, any `failed_permanent` needs a human.
--
-- RETENTION (design §4 requires one from day one): an unbounded store of inbound
-- email is a liability, not an asset. Phase 0.5 has no scheduler — pg_cron is not
-- enabled and building a worker is explicitly out of scope — so the policy is
-- documented and manual, and this index is what makes it cheap:
--
--   delete from public.inbound_emails
--    where received_at < now() - interval '90 days'
--      and status in ('ingested', 'failed_permanent');
--
-- Unresolved rows (`pending`, `failed_transient`) are deliberately excluded from
-- that statement: they are the reason the table exists.
create index if not exists inbound_emails_status_received_at_idx
    on public.inbound_emails using btree (status, received_at);

alter table public.inbound_emails enable row level security;

-- Deny first, then grant exactly the declared surface. A verb missing here is
-- denied, which is the point.
revoke all on table public.inbound_emails from anon, authenticated;

-- The identity SEQUENCE needs its own revoke. Supabase's default privileges
-- grant ALL on new sequences to anon and authenticated, and a table revoke does
-- not reach the sequence. `20260911235000_close_anon_grants_and_view_invoker.sql`
-- disables those defaults for objects created afterwards, but this migration
-- must not depend on that having run: an assertion that passes because another
-- file happened to land first is the "looks applied" failure mode this block
-- exists to catch.
revoke all on sequence public.inbound_emails_id_seq from anon, authenticated;

-- Owners read it to triage; the policy below is what actually gates the rows.
grant select on table public.inbound_emails to authenticated;

-- The Edge Function writes it as service_role. Nothing else writes it.
grant all on table public.inbound_emails to service_role;
grant usage, select on sequence public.inbound_emails_id_seq to service_role;

drop policy if exists "inbound_email_select_owner" on public.inbound_emails;
create policy "inbound_email_select_owner" on public.inbound_emails for select to authenticated using (
  public.is_admin()
);

-- Assert the end state. A migration that silently no-ops is worse than no
-- migration, because it looks applied — this repository has been bitten by that
-- twice already (the storage bucket, and REVOKE EXECUTE on functions owned by
-- supabase_admin). These checks run on every `db reset` and every deploy.
do $$
declare
  v_bad text;
  v_rls boolean;
begin
  -- 1. RLS on. Without it the grant below exposes every stored email body.
  select c.relrowsecurity
  into v_rls
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relname = 'inbound_emails';

  if v_rls is distinct from true then
    raise exception
      'RLS is not enabled on public.inbound_emails; it stores inbound email content (LGPD personal data)';
  end if;

  -- 2. anon holds nothing. Every verb is checked, not just SELECT: RLS does not
  --    gate TRUNCATE, so a TRUNCATE grant empties an RLS-protected table.
  if to_regrole('anon') is not null then
    select string_agg(p.priv, ', ')
    into v_bad
    from unnest(array['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER']) as p(priv)
    where has_table_privilege('anon', 'public.inbound_emails', p.priv);

    if v_bad is not null then
      raise exception
        'anon holds % on public.inbound_emails; it must hold none', v_bad;
    end if;
  end if;

  -- 2b. Same for the identity sequence: USAGE on it is enough to interfere
  --     with a table whose rows are otherwise protected.
  if to_regrole('anon') is not null then
    select string_agg(format('anon:%s', p.priv), ', ')
    into v_bad
    from unnest(array['USAGE','SELECT','UPDATE']) as p(priv)
    where has_sequence_privilege('anon', 'public.inbound_emails_id_seq', p.priv);

    if v_bad is not null then
      raise exception
        'anon holds % on public.inbound_emails_id_seq; it must hold none', v_bad;
    end if;
  end if;

  if to_regrole('authenticated') is not null then
    select string_agg(format('authenticated:%s', p.priv), ', ')
    into v_bad
    from unnest(array['USAGE','SELECT','UPDATE']) as p(priv)
    where has_sequence_privilege('authenticated', 'public.inbound_emails_id_seq', p.priv);

    if v_bad is not null then
      raise exception
        'authenticated holds % on public.inbound_emails_id_seq; it must hold none', v_bad;
    end if;
  end if;

  -- 3. authenticated reads and nothing else. Writing is the Edge Function's job.
  if to_regrole('authenticated') is not null then
    select string_agg(p.priv, ', ')
    into v_bad
    from unnest(array['INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER']) as p(priv)
    where has_table_privilege('authenticated', 'public.inbound_emails', p.priv);

    if v_bad is not null then
      raise exception
        'authenticated holds % on public.inbound_emails; only SELECT (gated on is_admin()) is allowed', v_bad;
    end if;
  end if;

  -- 4. The unique index exists. Without it idempotency degrades silently into
  --    duplicate notes on every provider retry, with no error anywhere.
  if not exists (
    select 1
    from pg_indexes
    where schemaname = 'public'
      and tablename = 'inbound_emails'
      and indexname = 'uq__inbound_emails__message_recipient'
  ) then
    raise exception
      'uq__inbound_emails__message_recipient is missing; the claim-before-work idempotency check has nothing to enforce it';
  end if;

  -- 5. A read policy exists. RLS with no policy denies everything, which would
  --    make the SELECT grant above a lie and leave failures untriageable.
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'inbound_emails'
      and policyname = 'inbound_email_select_owner'
  ) then
    raise exception
      'inbound_email_select_owner policy is missing; the ledger would be unreadable by anyone';
  end if;
end
$$;
